// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VRGamersWhoLift.Models.database;

#nullable disable

namespace VRGamersWhoLift.Migrations
{
    [DbContext(typeof(VRGamersWhoLiftContext))]
    [Migration("20260616202740_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VRGamersWhoLift.Models.Abstract.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasDiscriminator<string>("Discriminator").HasValue("User");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("VRGamersWhoLift.Models.Profile", b =>
                {
                    b.Property<string>("ProfileUsernameID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProfileUsernameID");

                    b.ToTable("profiles");

                    b.HasData(
                        new
                        {
                            ProfileUsernameID = "rarends",
                            Name = "robert_arends"
                        },
                        new
                        {
                            ProfileUsernameID = "swilkins",
                            Name = "samantha_wilkins"
                        },
                        new
                        {
                            ProfileUsernameID = "ngreyson",
                            Name = "nolan_greyson"
                        });
                });

            modelBuilder.Entity("VRGamersWhoLift.Models.users.Admin", b =>
                {
                    b.HasBaseType("VRGamersWhoLift.Models.Abstract.User");

                    b.HasDiscriminator().HasValue("Admin");

                    b.HasData(
                        new
                        {
                            Id = "66c0432f-cc51-44aa-81ea-7fdf9343000e",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "37ab9789-09d3-4b2e-82ec-c2cff5f80c6d",
                            Email = "robert.arends100@gitmail.com",
                            EmailConfirmed = false,
                            FirstName = "Robert",
                            LastName = "Arends",
                            LockoutEnabled = false,
                            MiddleName = "Charles",
                            Password = "Password",
                            PhoneNumberConfirmed = false,
                            Role = "a",
                            SecurityStamp = "64efbd09-2cfa-40be-89c6-d7acb4249512",
                            TwoFactorEnabled = false,
                            UserName = "rarends"
                        });
                });

            modelBuilder.Entity("VRGamersWhoLift.Models.users.Coach", b =>
                {
                    b.HasBaseType("VRGamersWhoLift.Models.Abstract.User");

                    b.HasDiscriminator().HasValue("Coach");

                    b.HasData(
                        new
                        {
                            Id = "bc5f7fa8-ca85-45de-8bd3-95acd1a3b125",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "19a3611c-a78e-456b-ac6d-62e6b8d9e170",
                            Email = "nolan.Greyson@viltrum.planet",
                            EmailConfirmed = false,
                            FirstName = "Nolan",
                            LastName = "Greyson",
                            LockoutEnabled = false,
                            MiddleName = "",
                            Password = "Password",
                            PhoneNumberConfirmed = false,
                            Role = "c",
                            SecurityStamp = "ac423206-21d5-4a50-9484-da96f1329599",
                            TwoFactorEnabled = false,
                            UserName = "ngreyson"
                        });
                });

            modelBuilder.Entity("VRGamersWhoLift.Models.users.Member", b =>
                {
                    b.HasBaseType("VRGamersWhoLift.Models.Abstract.User");

                    b.HasDiscriminator().HasValue("Member");

                    b.HasData(
                        new
                        {
                            Id = "c74b800c-1607-493f-99c5-cf7986515080",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f7c9f4bc-1a15-4cc6-b4d6-d5e599ed1df4",
                            Email = "Samantha.Wilkins@gitmail.com",
                            EmailConfirmed = false,
                            FirstName = "Samantha",
                            LastName = "Wilkins",
                            LockoutEnabled = false,
                            MiddleName = "Eve",
                            Password = "Password",
                            PhoneNumberConfirmed = false,
                            Role = "m",
                            SecurityStamp = "30a73f5e-b271-44a7-98a9-eb43f6c9fbde",
                            TwoFactorEnabled = false,
                            UserName = "swilkins"
                        });
                });

            modelBuilder.Entity("VRGamersWhoLift.Models.Profile", b =>
                {
                    b.HasOne("VRGamersWhoLift.Models.Abstract.User", "User")
                        .WithOne("Profile")
                        .HasForeignKey("VRGamersWhoLift.Models.Profile", "ProfileUsernameID")
                        .HasPrincipalKey("VRGamersWhoLift.Models.Abstract.User", "UserName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("VRGamersWhoLift.Models.Abstract.User", b =>
                {
                    b.Navigation("Profile")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
