// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VRGamersWhoLift.Models.database;

#nullable disable

namespace VRGamersWhoLift.Migrations
{
    [DbContext(typeof(VRGamersWhoLiftContext))]
    partial class UserContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VRGamersWhoLift.Models.Abstract.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserID");

                    b.ToTable("Users");

                    b.HasDiscriminator<string>("Discriminator").HasValue("User");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("VRGamersWhoLift.Models.users.Admin", b =>
                {
                    b.HasBaseType("VRGamersWhoLift.Models.Abstract.User");

                    b.HasDiscriminator().HasValue("Admin");

                    b.HasData(
                        new
                        {
                            UserID = 1,
                            Email = "robert.arends100@gitmail.com",
                            FirstName = "Robert",
                            LastName = "Arends",
                            MiddleName = "Charles",
                            Password = "Password",
                            UserType = "a"
                        });
                });

            modelBuilder.Entity("VRGamersWhoLift.Models.users.Coach", b =>
                {
                    b.HasBaseType("VRGamersWhoLift.Models.Abstract.User");

                    b.HasDiscriminator().HasValue("Coach");

                    b.HasData(
                        new
                        {
                            UserID = 3,
                            Email = "nolan.Greyson@viltrum.planet",
                            FirstName = "Nolan",
                            LastName = "Greyson",
                            MiddleName = "",
                            Password = "Password",
                            UserType = "c"
                        });
                });

            modelBuilder.Entity("VRGamersWhoLift.Models.users.Member", b =>
                {
                    b.HasBaseType("VRGamersWhoLift.Models.Abstract.User");

                    b.HasDiscriminator().HasValue("Member");

                    b.HasData(
                        new
                        {
                            UserID = 2,
                            Email = "Samantha.Wilkins@gitmail.com",
                            FirstName = "Samantha",
                            LastName = "Wilkins",
                            MiddleName = "Eve",
                            Password = "Password",
                            UserType = "m"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
